steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - 'terraform init || exit 1'
  dir: deployments/app1

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - 'terraform plan -out=terraform.plan -var="project_id=$PROJECT_ID"'
  dir: deployments/app1
# [END tf-plan]

# [START tf-parse for terraform validator]
- id: 'tf parse'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - 'terraform show -json terraform.plan > terraform.json'
  dir: deployments/app1
# [END tf-plan]

# [START tf-vet]
- id: 'tf validate'
  name: 'us-central1-docker.pkg.dev/$PROJECT_ID/terraform-vet/terraform-vet:latest'
  dir: deployments/app1
  entrypoint: 'sh'
  args:
  - '-c'
  - 'gcloud beta terraform vet terraform.json --verbosity=debug --policy-library=../../policy-library/'
# [END tf-vet]    
